var ISODate = require('isodate');
var jsonData = [
        {
                "_id" : "sPBCgZWFmhDSRx9z2",
                "householdDataTrustId" : "1279301",
                "householdRank" : 1,
                "firstName" : "TORRANESHA",
                "lastName" : "MOBBS",
                "middleName" : "DESHAE",
                "gender" : "Female",
                "dateOfBirth" : ISODate("1899-12-31T06:00:00Z"),
                "age" : 116,
                "officialEthnicity" : "Black",
                "calculatedEthnicity" : "Unknown",
                "address1" : "350 Dupree St",
                "address2" : "Null",
                "city" : "Pineville",
                "county" : "Rapides Parish",
                "countyId" : "2207900000",
                "countyFips" : "79",
                "countyNumber" : "40",
                "state" : "LA",
                "zip" : "71360-6838",
                "country" : "USA",
                "precinctId" : "N03",
                "precinctName" : "N03",
                "congressionalDistrict" : "5",
                "senateDistrict" : "29",
                "legislativeDistrict" : "26",
                "turf" : "<null>",
                "latitude" : 31.307791,
                "longitude" : -92.413719,
                "phone" : "<null><null>",
                "rncId" : 11374892958,
                "dtId" : "DC726AE8-7864-46FC-B3D0-507734567C82",
                "status" : "Active",
                "registrationDate" : ISODate("2014-10-06T05:00:00Z"),
                "officialParty" : "Democrat",
                "calculatedParty" : "Strong Dem",
                "stateVoterId" : "8173740",
                "votingHistory" : [ ],
                "voterScore" : {
                        "overall" : 0,
                        "general" : 0,
                        "primary" : 0,
                        "presidentialPrimary" : 0
                },
                "createdAt" : ISODate("2016-06-08T17:31:00.192Z"),
                "createdBy" : "0"
        },
        {
                "_id" : "8xu5z8FEYzTJMFHcy",
                "householdDataTrustId" : "1466613",
                "householdRank" : 1,
                "firstName" : "FREDDIE",
                "lastName" : "PRICE",
                "gender" : "Male",
                "dateOfBirth" : ISODate("1949-12-31T06:00:00Z"),
                "age" : 66,
                "officialEthnicity" : "Black",
                "calculatedEthnicity" : "African American",
                "religion" : "Protestant",
                "address1" : "10469 Highway 71",
                "address2" : "Null",
                "city" : "Colfax",
                "county" : "Grant Parish",
                "countyId" : "2204300000",
                "countyFips" : "43",
                "countyNumber" : "22",
                "ward" : "5",
                "state" : "LA",
                "zip" : "71417-5336",
                "country" : "USA",
                "precinctId" : "05 02",
                "precinctName" : "05 02",
                "congressionalDistrict" : "5",
                "senateDistrict" : "35",
                "legislativeDistrict" : "22",
                "turf" : "SWING",
                "latitude" : 31.558206,
                "longitude" : -92.727542,
                "phone" : "318-627-5028",
                "doNotCall" : true,
                "rncId" : 11373736014,
                "dtId" : "79A75DD4-5C77-48DA-8360-4006ED9796CD",
                "status" : "Active",
                "registrationDate" : ISODate("2009-10-12T05:00:00Z"),
                "officialParty" : "Democrat",
                "calculatedParty" : "Strong Dem",
                "stateVoterId" : "7526445",
                "votingHistory" : [
                        {
                                "year" : 2014,
                                "method" : "Early",
                                "party" : "Other",
                                "electionType" : "General"
                        },
                        {
                                "year" : 2012,
                                "method" : "Poll",
                                "party" : "Other",
                                "electionType" : "General"
                        },
                        {
                                "year" : 2012,
                                "method" : "Poll",
                                "party" : "Other",
                                "electionType" : "Presidential Primary"
                        },
                        {
                                "year" : 2011,
                                "method" : "Poll",
                                "party" : "Other",
                                "electionType" : "General"
                        },
                        {
                                "year" : 2011,
                                "method" : "Poll",
                                "party" : "Other",
                                "electionType" : "Primary"
                        },
                        {
                                "year" : 2010,
                                "method" : "Poll",
                                "party" : "Other",
                                "electionType" : "General"
                        },
                        {
                                "year" : 2010,
                                "method" : "Poll",
                                "party" : "Other",
                                "electionType" : "Primary"
                        }
                ],
                "voterScore" : {
                        "overall" : 3,
                        "general" : 3,
                        "primary" : 1,
                        "presidentialPrimary" : 1
                },
                "createdAt" : ISODate("2016-06-08T17:31:00.477Z"),
                "createdBy" : "0"
        },
        {
                "_id" : "pCiez8D88EQbmjNAG",
                "householdDataTrustId" : "1730113",
                "householdRank" : 1,
                "firstName" : "WILLIAM",
                "lastName" : "STEWART",
                "middleName" : "RYDER",
                "gender" : "Male",
                "dateOfBirth" : ISODate("1969-12-31T06:00:00Z"),
                "age" : 46,
                "officialEthnicity" : "White",
                "calculatedEthnicity" : "White",
                "religion" : "Protestant",
                "address1" : "2498 Highway 34",
                "address2" : "Null",
                "city" : "Dodson",
                "county" : "Winn Parish",
                "countyId" : "2212700000",
                "countyFips" : "127",
                "countyNumber" : "64",
                "ward" : "5",
                "state" : "LA",
                "zip" : "71422-3689",
                "country" : "USA",
                "precinctId" : "05 04",
                "precinctName" : "05 04",
                "congressionalDistrict" : "5",
                "senateDistrict" : "35",
                "legislativeDistrict" : "13",
                "turf" : "WEAK GOP",
                "latitude" : 32.078209,
                "longitude" : -92.58516,
                "phone" : "318-648-1397",
                "doNotCall" : false,
                "rncId" : 11375681709,
                "dtId" : "DB7FBDE1-2EBA-4219-A04E-EA0248680597",
                "status" : "Active",
                "registrationDate" : ISODate("2007-09-10T05:00:00Z"),
                "officialParty" : "Republican",
                "calculatedParty" : "Weak GOP",
                "stateVoterId" : "7158912",
                "votingHistory" : [ ],
                "voterScore" : {
                        "overall" : 0,
                        "general" : 0,
                        "primary" : 0,
                        "presidentialPrimary" : 0
                },
                "createdAt" : ISODate("2016-06-08T17:31:00.492Z"),
                "createdBy" : "0"
        }
];

module.exports.data = jsonData;
